In [1]:
# Import Required Libraries
import numpy as np
import tensorflow as tf
!pip install tensorflow-hub
!pip install tensorflow-datasets
import tensorflow_hub as hub
import tensorflow_datasets as tfds

Defaulting to user installation because normal site-packages is not writeable
Defaulting to user installation because normal site-packages is not writeable



In [2]:
# Load IMDB dataset
dataset_name = "imdb_reviews"
(train_data, valid_data), dataset_info = tfds.load(
    dataset_name, 
    split=("train", "test"), 
    as_supervised=True, 
    with_info=True
)

In [3]:
#Tensorflow Version check
print("TensorFlow Version:", tf.__version__)

TensorFlow Version: 2.18.0


In [4]:
import tensorflow_datasets as tfds

# Load Dataset
train_data, validation_data, test_data = tfds.load(
    name="imdb_reviews",
    split=('train[:60%]', 'train[60%:]', 'test'),
    as_supervised=True
)

print("Dataset Loaded Successfully!")


Dataset Loaded Successfully!


In [5]:
#GPU availability:
train_data
print("GPU is", "available" if tf.config.list_physical_devices("GPU") else "NOT AVAILABLE")

GPU is NOT AVAILABLE


In [6]:
# Inspect Data
train_example_batch, train_labels_batch = next(iter(train_data.batch(10)))
for i in range(10):
    print(f"Review: {train_example_batch[i].numpy()}")
    print(f"Label: {train_labels_batch[i].numpy()}\n")

Review: b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it."
Label: 0

Review: b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell asleep because the film was rubbish

In [7]:
train_example_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [8]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0])>

In [9]:
import tensorflow as tf
import tensorflow_hub as hub

print("TensorFlow Version:", tf.__version__)
print("TensorFlow Hub Version:", hub.__version__)


TensorFlow Version: 2.18.0
TensorFlow Hub Version: 0.16.1


In [10]:
import tensorflow_hub as hub
import tensorflow as tf

# Load the TensorFlow Hub embedding layer
hub_url = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"  # Example URL
hub_layer = hub.KerasLayer(hub_url, input_shape=[], dtype=tf.string, trainable=False)

print("Hub Layer Loaded Successfully!")


Hub Layer Loaded Successfully!


In [11]:
hub_layer(train_example_batch[:3])

<tf.Tensor: shape=(3, 20), dtype=float32, numpy=
array([[ 1.765786  , -3.882232  ,  3.9134233 , -1.5557289 , -3.3362343 ,
        -1.7357955 , -1.9954445 ,  1.2989551 ,  5.081598  , -1.1041286 ,
        -2.0503852 , -0.72675157, -0.65675956,  0.24436149, -3.7208383 ,
         2.0954835 ,  2.2969332 , -2.0689783 , -2.9489717 , -1.1315987 ],
       [ 1.8804485 , -2.5852382 ,  3.4066997 ,  1.0982676 , -4.056685  ,
        -4.891284  , -2.785554  ,  1.3874227 ,  3.8476458 , -0.9256538 ,
        -1.896706  ,  1.2113281 ,  0.11474707,  0.76209456, -4.8791065 ,
         2.906149  ,  4.7087674 , -2.3652055 , -3.5015898 , -1.6390051 ],
       [ 0.71152234, -0.6353217 ,  1.7385626 , -1.1168286 , -0.5451594 ,
        -1.1808156 ,  0.09504455,  1.4653089 ,  0.66059524,  0.79308075,
        -2.2268345 ,  0.07446612, -1.4075904 , -0.70645386, -1.907037  ,
         1.4419787 ,  1.9551861 , -0.42660055, -2.8022065 ,  0.43727064]],
      dtype=float32)>

In [12]:
# Load dataset (replace this with your dataset loading code)
dataset_name = "imdb_reviews"
data, info = tfds.load(dataset_name, with_info=True, as_supervised=True)
train_data, test_data = data['train'], data['test']

In [13]:
import tensorflow as tf
import tensorflow_hub as hub

# Load the TensorFlow Hub embedding layer
hub_url = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"  # Example URL
hub_layer = hub.KerasLayer(hub_url, dtype=tf.string, trainable=False)

# Define the input layer
input_text = tf.keras.layers.Input(shape=(), dtype=tf.string, name="text_input")

# Workaround: Use a Lambda layer to correctly pass input
embedding = tf.keras.layers.Lambda(lambda x: hub_layer(tf.cast(x, tf.string)))(input_text)

# Add Dense layers
dense_1 = tf.keras.layers.Dense(16, activation='relu')(embedding)
output = tf.keras.layers.Dense(1, activation='sigmoid')(dense_1)

# Create model
model = tf.keras.Model(inputs=input_text, outputs=output)

In [14]:
# Print Model Summary
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ text_input (InputLayer)              │ (None)                      │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lambda (Lambda)                      │ (None, 20)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 16)                  │             336 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │              17 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 353 (1.38 KB)

 Trainable params: 353 (1.38 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
# Compile the model
model.compile(optimizer='adam', 
              loss=tf.keras.losses.BinaryCrossentropy(from_logits=False),  # from_logits=False for sigmoid
              metrics=['accuracy'])

In [16]:
for text, label in train_data.take(1):
    print("Text:", text.numpy(), "Type:", type(text.numpy()))
    print("Label:", label.numpy())

Text: b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it." Type: <class 'bytes'>
Label: 0


In [17]:
# Train the model

history = model.fit(
    train_data.shuffle(10000).batch(100),  
    validation_data=validation_data.batch(100),  
    epochs=25,  
    verbose=1  
)

Epoch 1/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 19ms/step - accuracy: 0.5811 - loss: 1.0890 - val_accuracy: 0.6806 - val_loss: 0.5966
Epoch 2/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.6944 - loss: 0.5882 - val_accuracy: 0.7021 - val_loss: 0.5751
Epoch 3/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.7041 - loss: 0.5713 - val_accuracy: 0.7088 - val_loss: 0.5667
Epoch 4/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - accuracy: 0.7088 - loss: 0.5622 - val_accuracy: 0.7124 - val_loss: 0.5625
Epoch 5/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.7074 - loss: 0.5651 - val_accuracy: 0.7151 - val_loss: 0.5569
Epoch 6/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.7108 - loss: 0.5606 - val_accuracy: 0.7218 - val_loss: 0.5549
Epoch 7/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.7153 - loss: 0.5542 - val_accuracy: 0.7225 - val_loss: 0.5515
Epoch 8/25
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.7163 - loss: 0.5548 - val_accu

In [18]:
results = model.evaluate(test_data.batch(100), verbose=2)
for name, value in zip(model.metrics_names, results):
    print("%s: %.3f" % (name, value))

250/250 - 3s - 13ms/step - accuracy: 0.7218 - loss: 0.5490
loss: 0.549
compile_metrics: 0.722
